title: OES toolbox
description: Helping out with optical emission spectroscopy
author: "Julian Held"

theme: minima

base_url: /oes-toolbox
repository: mimurrayy/oes-toolbox

# Minima social links
github_username: mimurrayy

# Minima: show excerpts in the frontpage
show_excerpts: false

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md

include:
    - _pages

exclude: 
